apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rapp-ui.fullname" . }}-application-properties
  labels:
    {{- include "rapp-ui.labels" . | nindent 4 }}
data:
  .env: |-
    VITE_APP_BACKEND_URL={{ .Values.application.backendurl }}
    VITE_APP_ENV=development
    SKIP_PREFLIGHT_CHECK={{ .Values.application.skippreflight }}
    DISABLE_ESLINT_PLUGIN={{ .Values.application.disableeslint }}
    VITE_APP_MAPBOX_TOKEN={{ .Values.application.mapboxtoken }}
