apiVersion: v1
kind: Service
metadata:
  name: {{ include "rapp-ui.fullname" . }}
  labels:
    {{- include "rapp-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ ternary .Values.service.httpsPort .Values.service.httpPort (eq (include "rapp-ui.is-tls-enabled" .) "true") }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rapp-ui.selectorLabels" . | nindent 4 }}
