{{- if .Values.virtualHost.enabled }}
{{- if eq (include "rapp-ui.is-tls-enabled" .) "true" }}
{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1/Certificate" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rapp-ui.labels" . | nindent 4 }}
    {{- include "rapp-ui.selectorLabels" . | nindent 4 }}
  name: {{ include "get-internal-ca-fullname" . }}
spec:
  ca:
    secretName: {{ include "get-internal-ca-secret-fullname" . }}
{{- end -}}
{{- end -}}
{{- end -}}